disabled_rules:
    - multiple_closures_with_trailing_closure
excluded:
    - build
identifier_name:
    excluded:
        - id
type_name:
    min_length: 3
    max_length:
        warning: 50
        error: 60
