disabled_rules:
    - multiple_closures_with_trailing_closure
    - opening_brace # we do want this normally, but with mutli-line if's not always
    - large_tuple
excluded:
    - build
identifier_name:
    excluded:
        - id
type_name:
    min_length: 3
    max_length:
        warning: 50
        error: 60
