name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: xcodebuild -project Zwaai.xcodeproj -configuration Debug -scheme Zwaai -sdk iphonesimulator -disableAutomaticPackageResolution

